; <?php exit; ?>
MYSQL_DATABASE_NAME = "prueba1"
MYSQL_USER = "root"
MYSQL_PASSWORD = ""

MMYSQL_DATABASE_NAME = "epiz_32878913_php_login_datebase2"
MMYSQL_USER = "epiz_32878913"
MMYSQL_PASSWORD = "DJTklQhMplIld"
SERVER_NAME=""